export const BIO_PAGE = "BIO PAGE";
export const SKILLS_PAGE = "SKILLS PAGE";
export const EDUCATION_PAGE = "EDUCATION PAGE";
export const WORK_EXPERIENCE_PAGE = "WORK EXPERIENCE PAGE";
export const CERTIFICATION_PAGE = "CERTIFICATION PAGE";
